### ISSUE TITLE
Nav menu code could be refactored

### ISSUE THREAD

**Issue by meganwalter** [andrewpeterwatson/portfolio#12]
Class 05 pair assignment, Megan and Andrew will refactor app.js lines 13 to 31 to one function.

**Comment by andrewpeterwatson** [comment]
`
var articleView = {};

articleView.mainNav = function() {
  $('nav').on('click', 'li', function() {
    $('.tab-content').hide();
    $('#' + $(this).data('content')).fadeIn(500);
  });
  $('nav ul li:first').click();
};
$(document).ready(function() {
  articleView.mainNav();
});
`
Refactored code to scale down and make more concise.
